apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           securityContext:
             allowPrivilegeEscalation: false
             runAsNonRoot: true      # опционально, но хорошая практика
             runAsUser: 1000         # опционально
           ports:
             - containerPort: PORT_CONTAINER
           env:
             - name: MINGLO_DB_URL
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_DB_URL
             - name: MINGLO_TESTING_MODULE
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_TESTING_MODULE
             - name: MINGLO_SWAGGER
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_SWAGGER
             - name: MINGLO_TRUST_PROXY
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_TRUST_PROXY
             - name: MINGLO_CORS
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_CORS
             - name: MINGLO_CORS_ORIGINS
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_CORS_ORIGINS
             - name: MINGLO_CORS_CREDENTIALS
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_CORS_CREDENTIALS
             - name: MINGLO_PORT
               valueFrom:
                 secretKeyRef:
                   name: minglo-backend-production-config-secret
                   key: MINGLO_PORT
