// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { config } from 'dotenv';
// this import (envFilePaths) should use absolute path
import { envFilePaths } from '../../libs/dynamic-config/src/env-file-paths';

config({
  path: envFilePaths,
});

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['MINGLO_DB_URL'],
  },
});
