export enum AccountType {
  PERSONAL = 'PERSONAL',
  BUSINESS = 'BUSINESS',
}

export enum WS_EVENTS {
  NOTIFICATION = 'NOTIFICATION',
}

export enum NotificationType {
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  SUBSCRIPTION_EXPIRING_7_DAYS = 'SUBSCRIPTION_EXPIRING_7_DAYS',
  SUBSCRIPTION_EXPIRING_1_DAY = 'SUBSCRIPTION_EXPIRING_1_DAY',
}
