export const WS_CLIENT_EVENTS = {
  MESSAGE_SEND: 'MESSAGE_SEND',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
  CONVERSATION_JOIN: 'CONVERSATION_JOIN',
} as const;

export const WS_SERVER_EVENTS = {
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  USER_TYPING: 'USER_TYPING',
} as const;
